name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        pre-build-command: "pip install cloud_sptheme sphinx_rtd_theme"
    - name: Disable Jekyll
      run: sudo touch ./_build/html/.nojekyll
    - uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: _build/html/ # The folder the action should deploy.
