name: Sphinx Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        pre-build-command: "pip install cloud_sptheme sphinx_rtd_theme"
    - uses: actions/upload-artifact@v1
      with:
        name: build-result
        path: ./_build
